name: Build TeOS Kernel

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt install -y gcc-multilib
      - name: Compile Kernel
        run: |
          cd system/kernel
          i686-elf-gcc -ffreestanding -c main.c -o main.o
          i686-elf-ld -Ttext 0x1000 -o kernel.bin main.o --oformat binary
          
